version: "2"

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  enable:
    - bodyclose
    - canonicalheader
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck

  settings:
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true

    sloglint:
      attr-only: true
      context: all
      static-msg: true
      no-raw-keys: true
      key-naming-case: snake
      args-on-sep-lines: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
