// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Comparison struct {
	ID         int64      `json:"id"`
	WinnerID   int64      `json:"winner_id"`
	WinnerName string     `json:"winner_name"`
	LoserID    int64      `json:"loser_id"`
	LoserName  string     `json:"loser_name"`
	CreatedAt  *time.Time `json:"created_at"`
}

type Restaurant struct {
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	Cuisine   string     `json:"cuisine"`
	Elo       float64    `json:"elo"`
	Score     float64    `json:"score"`
	Position  int64      `json:"position"`
	CreatedAt *time.Time `json:"created_at"`
	IsSeed    bool       `json:"is_seed"`
}
