// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountRestaurants(ctx context.Context) (int64, error)
	CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error)
	CreateSeedRestaurant(ctx context.Context, arg CreateSeedRestaurantParams) (Restaurant, error)
	DeleteAllComparisons(ctx context.Context) error
	DeleteAllRestaurants(ctx context.Context) error
	DeleteNonSeedRestaurants(ctx context.Context) error
	DeleteRestaurant(ctx context.Context, id int64) error
	GetAllComparisons(ctx context.Context) ([]Comparison, error)
	GetAllRestaurants(ctx context.Context) ([]Restaurant, error)
	GetRestaurantByID(ctx context.Context, id int64) (Restaurant, error)
	RecordComparison(ctx context.Context, arg RecordComparisonParams) error
	UpdatePositions(ctx context.Context, position int64) error
	UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) error
}

var _ Querier = (*Queries)(nil)
