// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const countRestaurants = `-- name: CountRestaurants :one
SELECT COUNT(*) FROM restaurants
`

func (q *Queries) CountRestaurants(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRestaurants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (name, cuisine, elo, score, position)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, cuisine, elo, score, position, created_at, is_seed
`

type CreateRestaurantParams struct {
	Name     string  `json:"name"`
	Cuisine  string  `json:"cuisine"`
	Elo      float64 `json:"elo"`
	Score    float64 `json:"score"`
	Position int64   `json:"position"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, createRestaurant,
		arg.Name,
		arg.Cuisine,
		arg.Elo,
		arg.Score,
		arg.Position,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cuisine,
		&i.Elo,
		&i.Score,
		&i.Position,
		&i.CreatedAt,
		&i.IsSeed,
	)
	return i, err
}

const createSeedRestaurant = `-- name: CreateSeedRestaurant :one
INSERT INTO restaurants (name, cuisine, elo, score, position, is_seed)
VALUES (?, ?, ?, ?, ?, 1)
RETURNING id, name, cuisine, elo, score, position, created_at, is_seed
`

type CreateSeedRestaurantParams struct {
	Name     string  `json:"name"`
	Cuisine  string  `json:"cuisine"`
	Elo      float64 `json:"elo"`
	Score    float64 `json:"score"`
	Position int64   `json:"position"`
}

func (q *Queries) CreateSeedRestaurant(ctx context.Context, arg CreateSeedRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, createSeedRestaurant,
		arg.Name,
		arg.Cuisine,
		arg.Elo,
		arg.Score,
		arg.Position,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cuisine,
		&i.Elo,
		&i.Score,
		&i.Position,
		&i.CreatedAt,
		&i.IsSeed,
	)
	return i, err
}

const deleteAllComparisons = `-- name: DeleteAllComparisons :exec
DELETE FROM comparisons
`

func (q *Queries) DeleteAllComparisons(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllComparisons)
	return err
}

const deleteAllRestaurants = `-- name: DeleteAllRestaurants :exec
DELETE FROM restaurants
`

func (q *Queries) DeleteAllRestaurants(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRestaurants)
	return err
}

const deleteNonSeedRestaurants = `-- name: DeleteNonSeedRestaurants :exec
DELETE FROM restaurants WHERE is_seed = 0
`

func (q *Queries) DeleteNonSeedRestaurants(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteNonSeedRestaurants)
	return err
}

const deleteRestaurant = `-- name: DeleteRestaurant :exec
DELETE FROM restaurants WHERE id = ?
`

func (q *Queries) DeleteRestaurant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRestaurant, id)
	return err
}

const getAllComparisons = `-- name: GetAllComparisons :many
SELECT id, winner_id, winner_name, loser_id, loser_name, created_at FROM comparisons ORDER BY created_at DESC
`

func (q *Queries) GetAllComparisons(ctx context.Context) ([]Comparison, error) {
	rows, err := q.db.QueryContext(ctx, getAllComparisons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.WinnerID,
			&i.WinnerName,
			&i.LoserID,
			&i.LoserName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRestaurants = `-- name: GetAllRestaurants :many
SELECT id, name, cuisine, elo, score, position, created_at, is_seed FROM restaurants ORDER BY position ASC
`

func (q *Queries) GetAllRestaurants(ctx context.Context) ([]Restaurant, error) {
	rows, err := q.db.QueryContext(ctx, getAllRestaurants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Restaurant{}
	for rows.Next() {
		var i Restaurant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cuisine,
			&i.Elo,
			&i.Score,
			&i.Position,
			&i.CreatedAt,
			&i.IsSeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT id, name, cuisine, elo, score, position, created_at, is_seed FROM restaurants WHERE id = ? LIMIT 1
`

func (q *Queries) GetRestaurantByID(ctx context.Context, id int64) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, getRestaurantByID, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cuisine,
		&i.Elo,
		&i.Score,
		&i.Position,
		&i.CreatedAt,
		&i.IsSeed,
	)
	return i, err
}

const recordComparison = `-- name: RecordComparison :exec
INSERT INTO comparisons (winner_id, winner_name, loser_id, loser_name)
VALUES (?, ?, ?, ?)
`

type RecordComparisonParams struct {
	WinnerID   int64  `json:"winner_id"`
	WinnerName string `json:"winner_name"`
	LoserID    int64  `json:"loser_id"`
	LoserName  string `json:"loser_name"`
}

func (q *Queries) RecordComparison(ctx context.Context, arg RecordComparisonParams) error {
	_, err := q.db.ExecContext(ctx, recordComparison,
		arg.WinnerID,
		arg.WinnerName,
		arg.LoserID,
		arg.LoserName,
	)
	return err
}

const updatePositions = `-- name: UpdatePositions :exec
UPDATE restaurants
SET position = position + 1
WHERE position >= ?
`

func (q *Queries) UpdatePositions(ctx context.Context, position int64) error {
	_, err := q.db.ExecContext(ctx, updatePositions, position)
	return err
}

const updateRestaurant = `-- name: UpdateRestaurant :exec
UPDATE restaurants
SET elo = ?, score = ?, position = ?
WHERE id = ?
`

type UpdateRestaurantParams struct {
	Elo      float64 `json:"elo"`
	Score    float64 `json:"score"`
	Position int64   `json:"position"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, updateRestaurant,
		arg.Elo,
		arg.Score,
		arg.Position,
		arg.ID,
	)
	return err
}
